export const SUPPORTED_LANGUAGES = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "es", name: "Spanish", nativeName: "Español" },
  { code: "fr", name: "French", nativeName: "Français" },
  { code: "de", name: "German", nativeName: "Deutsch" },
  { code: "it", name: "Italian", nativeName: "Italiano" },
  { code: "pt", name: "Portuguese", nativeName: "Português" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands" },
  { code: "ru", name: "Russian", nativeName: "Русский" },
  { code: "zh", name: "Chinese", nativeName: "中文" },
  { code: "ja", name: "Japanese", nativeName: "日本語" },
  { code: "ko", name: "Korean", nativeName: "한국어" },
  { code: "ar", name: "Arabic", nativeName: "العربية" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { code: "ur", name: "Urdu", nativeName: "اردو" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt" },
  { code: "th", name: "Thai", nativeName: "ไทย" },
  { code: "pl", name: "Polish", nativeName: "Polski" },
  { code: "uk", name: "Ukrainian", nativeName: "Українська" },
  { code: "cs", name: "Czech", nativeName: "Čeština" },
  { code: "sv", name: "Swedish", nativeName: "Svenska" },
  { code: "da", name: "Danish", nativeName: "Dansk" },
  { code: "fi", name: "Finnish", nativeName: "Suomi" },
  { code: "no", name: "Norwegian", nativeName: "Norsk" },
  { code: "el", name: "Greek", nativeName: "Ελληνικά" },
  { code: "he", name: "Hebrew", nativeName: "עברית" },
  { code: "ro", name: "Romanian", nativeName: "Română" },
  { code: "hu", name: "Hungarian", nativeName: "Magyar" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia" },
  { code: "ms", name: "Malay", nativeName: "Bahasa Melayu" },
  { code: "tl", name: "Filipino", nativeName: "Filipino" },
  { code: "sw", name: "Swahili", nativeName: "Kiswahili" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá" },
  { code: "ig", name: "Igbo", nativeName: "Igbo" },
  { code: "ha", name: "Hausa", nativeName: "Hausa" },
  { code: "zu", name: "Zulu", nativeName: "isiZulu" },
  { code: "af", name: "Afrikaans", nativeName: "Afrikaans" },
  { code: "sq", name: "Albanian", nativeName: "Shqip" },
  { code: "hy", name: "Armenian", nativeName: "Հայերեն" },
  { code: "az", name: "Azerbaijani", nativeName: "Azərbaycan" },
  { code: "eu", name: "Basque", nativeName: "Euskara" },
  { code: "be", name: "Belarusian", nativeName: "Беларуская" },
  { code: "bs", name: "Bosnian", nativeName: "Bosanski" },
  { code: "bg", name: "Bulgarian", nativeName: "Български" },
  { code: "hr", name: "Croatian", nativeName: "Hrvatski" },
  { code: "et", name: "Estonian", nativeName: "Eesti" },
  { code: "ka", name: "Georgian", nativeName: "ქართული" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
  { code: "km", name: "Khmer", nativeName: "ភាសាខ្មែរ" },
  { code: "lo", name: "Lao", nativeName: "ລາວ" },
  { code: "lv", name: "Latvian", nativeName: "Latviešu" },
  { code: "lt", name: "Lithuanian", nativeName: "Lietuvių" },
  { code: "mk", name: "Macedonian", nativeName: "Македонски" },
  { code: "mt", name: "Maltese", nativeName: "Malti" },
  { code: "mr", name: "Marathi", nativeName: "मराठी" },
  { code: "mn", name: "Mongolian", nativeName: "Монгол" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
  { code: "si", name: "Sinhala", nativeName: "සිංහල" },
  { code: "sk", name: "Slovak", nativeName: "Slovenčina" },
  { code: "sl", name: "Slovenian", nativeName: "Slovenščina" },
  { code: "so", name: "Somali", nativeName: "Soomaali" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { code: "tl", name: "Tagalog", nativeName: "Tagalog" },
  { code: "ug", name: "Uyghur", nativeName: "ئۇيغۇرچە" },
  { code: "uz", name: "Uzbek", nativeName: "O'zbek" },
  { code: "cy", name: "Welsh", nativeName: "Cymraeg" },
  { code: "yi", name: "Yiddish", nativeName: "ייִדיש" },
];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.search": "Search",
    "nav.favorites": "Favorites",
    "nav.liveTv": "Live TV",
    "nav.podcasts": "Podcasts",
    "nav.weather": "Weather",
    "nav.stocks": "Stocks",
    "nav.elections": "Elections",
    "nav.crypto": "Crypto",
    "nav.language": "Language",
    "home.title": "Top Stories",
    "home.subtitle": "The latest news from around the world",
    "home.trending": "Trending",
    "home.forYou": "For You",
    "search.placeholder": "Search news...",
    "search.title": "Search Results",
    "search.noResults": "No results found",
    "favorites.title": "Saved Articles",
    "favorites.empty": "No saved articles yet",
    "favorites.emptyHint": "Tap the heart icon on any article to save it",
    "weather.title": "Weather",
    "weather.forecast": "5-Day Forecast",
    "stocks.title": "Stock Market",
    "stocks.gainers": "Top Gainers",
    "stocks.losers": "Top Losers",
    "crypto.title": "Cryptocurrency",
    "crypto.marketCap": "Market Cap",
    "crypto.volume": "24h Volume",
    "elections.title": "Election Results",
    "elections.live": "LIVE",
    "liveTv.title": "Live TV News",
    "liveTv.categories": "Channels",
    "podcasts.title": "News Podcasts",
    "podcasts.latest": "Latest Episodes",
    "factCheck.verified": "Verified",
    "factCheck.unverified": "Unverified",
    "factCheck.disputed": "Disputed",
    "factCheck.satire": "Satire",
    "common.loadMore": "Load More",
    "common.loading": "Loading...",
    "common.error": "Something went wrong",
    "common.retry": "Retry",
    "common.back": "Back",
    "common.share": "Share",
    "common.save": "Save",
    "common.saved": "Saved",
    "common.readMore": "Read Original",
    "common.min": "min read",
  },
  es: {
    "nav.home": "Inicio",
    "nav.search": "Buscar",
    "nav.favorites": "Favoritos",
    "nav.liveTv": "TV en Vivo",
    "nav.podcasts": "Podcasts",
    "nav.weather": "Clima",
    "nav.stocks": "Bolsa",
    "nav.elections": "Elecciones",
    "nav.crypto": "Cripto",
    "nav.language": "Idioma",
    "home.title": "Principales Noticias",
    "home.subtitle": "Las últimas noticias de todo el mundo",
    "home.trending": "Tendencias",
    "home.forYou": "Para Ti",
    "search.placeholder": "Buscar noticias...",
    "search.title": "Resultados de Búsqueda",
    "search.noResults": "No se encontraron resultados",
    "favorites.title": "Artículos Guardados",
    "favorites.empty": "Aún no hay artículos guardados",
    "favorites.emptyHint": "Toca el ícono de corazón en cualquier artículo para guardarlo",
    "weather.title": "Clima",
    "weather.forecast": "Pronóstico de 5 Días",
    "stocks.title": "Mercado de Valores",
    "stocks.gainers": "Mayores Subidas",
    "stocks.losers": "Mayores Bajas",
    "crypto.title": "Criptomonedas",
    "crypto.marketCap": "Capitalización",
    "crypto.volume": "Volumen 24h",
    "elections.title": "Resultados Electorales",
    "elections.live": "EN VIVO",
    "liveTv.title": "TV en Vivo",
    "liveTv.categories": "Canales",
    "podcasts.title": "Podcasts de Noticias",
    "podcasts.latest": "Últimos Episodios",
    "factCheck.verified": "Verificado",
    "factCheck.unverified": "Sin Verificar",
    "factCheck.disputed": "Disputado",
    "factCheck.satire": "Sátira",
    "common.loadMore": "Cargar Más",
    "common.loading": "Cargando...",
    "common.error": "Algo salió mal",
    "common.retry": "Reintentar",
    "common.back": "Volver",
    "common.share": "Compartir",
    "common.save": "Guardar",
    "common.saved": "Guardado",
    "common.readMore": "Leer Original",
    "common.min": "min de lectura",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.search": "Rechercher",
    "nav.favorites": "Favoris",
    "nav.liveTv": "TV en Direct",
    "nav.podcasts": "Podcasts",
    "nav.weather": "Météo",
    "nav.stocks": "Bourse",
    "nav.elections": "Élections",
    "nav.crypto": "Crypto",
    "nav.language": "Langue",
    "home.title": "À la Une",
    "home.subtitle": "Les dernières actualités du monde entier",
    "home.trending": "Tendances",
    "home.forYou": "Pour Vous",
    "search.placeholder": "Rechercher des actualités...",
    "search.title": "Résultats de Recherche",
    "search.noResults": "Aucun résultat trouvé",
    "favorites.title": "Articles Sauvegardés",
    "favorites.empty": "Pas encore d'articles sauvegardés",
    "favorites.emptyHint": "Appuyez sur l'icône cœur sur n'importe quel article pour le sauvegarder",
    "weather.title": "Météo",
    "weather.forecast": "Prévisions sur 5 Jours",
    "stocks.title": "Marché Boursier",
    "stocks.gainers": "Plus Fortes Hausse",
    "stocks.losers": "Plus Fortes Baisses",
    "crypto.title": "Cryptomonnaies",
    "crypto.marketCap": "Capitalisation",
    "crypto.volume": "Volume 24h",
    "elections.title": "Résultats Électoraux",
    "elections.live": "EN DIRECT",
    "liveTv.title": "TV en Direct",
    "liveTv.categories": "Chaînes",
    "podcasts.title": "Podcasts d'Actualités",
    "podcasts.latest": "Derniers Épisodes",
    "factCheck.verified": "Vérifié",
    "factCheck.unverified": "Non Vérifié",
    "factCheck.disputed": "Contesté",
    "factCheck.satire": "Satire",
    "common.loadMore": "Charger Plus",
    "common.loading": "Chargement...",
    "common.error": "Une erreur s'est produite",
    "common.retry": "Réessayer",
    "common.back": "Retour",
    "common.share": "Partager",
    "common.save": "Sauvegarder",
    "common.saved": "Sauvegardé",
    "common.readMore": "Lire l'Original",
    "common.min": "min de lecture",
  },
  de: {
    "nav.home": "Startseite",
    "nav.search": "Suchen",
    "nav.favorites": "Favoriten",
    "nav.liveTv": "Live-TV",
    "nav.podcasts": "Podcasts",
    "nav.weather": "Wetter",
    "nav.stocks": "Börse",
    "nav.elections": "Wahlen",
    "nav.crypto": "Krypto",
    "nav.language": "Sprache",
    "home.title": "Top-Nachrichten",
    "home.subtitle": "Die neuesten Nachrichten aus der ganzen Welt",
    "home.trending": "Im Trend",
    "home.forYou": "Für Dich",
    "search.placeholder": "Nachrichten suchen...",
    "search.title": "Suchergebnisse",
    "search.noResults": "Keine Ergebnisse gefunden",
    "favorites.title": "Gespeicherte Artikel",
    "favorites.empty": "Noch keine gespeicherten Artikel",
    "favorites.emptyHint": "Tippe auf das Herz-Symbol bei einem Artikel, um ihn zu speichern",
    "weather.title": "Wetter",
    "weather.forecast": "5-Tage-Vorhersage",
    "stocks.title": "Aktienmarkt",
    "stocks.gainers": "Top-Gewinner",
    "stocks.losers": "Top-Verlierer",
    "crypto.title": "Kryptowährungen",
    "crypto.marketCap": "Marktkapitalisierung",
    "crypto.volume": "24h-Volumen",
    "elections.title": "Wahlergebnisse",
    "elections.live": "LIVE",
    "liveTv.title": "Live-TV-Nachrichten",
    "liveTv.categories": "Sender",
    "podcasts.title": "Nachrichten-Podcasts",
    "podcasts.latest": "Neueste Episoden",
    "factCheck.verified": "Verifiziert",
    "factCheck.unverified": "Nicht Verifiziert",
    "factCheck.disputed": "Umstritten",
    "factCheck.satire": "Satire",
    "common.loadMore": "Mehr laden",
    "common.loading": "Laden...",
    "common.error": "Etwas ist schiefgelaufen",
    "common.retry": "Erneut versuchen",
    "common.back": "Zurück",
    "common.share": "Teilen",
    "common.save": "Speichern",
    "common.saved": "Gespeichert",
    "common.readMore": "Original lesen",
    "common.min": "Min. Lesezeit",
  },
  zh: {
    "nav.home": "首页",
    "nav.search": "搜索",
    "nav.favorites": "收藏",
    "nav.liveTv": "直播",
    "nav.podcasts": "播客",
    "nav.weather": "天气",
    "nav.stocks": "股票",
    "nav.elections": "选举",
    "nav.crypto": "加密货币",
    "nav.language": "语言",
    "home.title": "头条新闻",
    "home.subtitle": "来自世界各地的最新消息",
    "home.trending": "热门",
    "home.forYou": "为你推荐",
    "search.placeholder": "搜索新闻...",
    "search.title": "搜索结果",
    "search.noResults": "未找到结果",
    "favorites.title": "已保存的文章",
    "favorites.empty": "暂无保存的文章",
    "favorites.emptyHint": "点击任何文章上的心形图标即可保存",
    "weather.title": "天气",
    "weather.forecast": "5天预报",
    "stocks.title": "股票市场",
    "stocks.gainers": "涨幅榜",
    "stocks.losers": "跌幅榜",
    "crypto.title": "加密货币",
    "crypto.marketCap": "市值",
    "crypto.volume": "24小时成交量",
    "elections.title": "选举结果",
    "elections.live": "直播",
    "liveTv.title": "电视直播",
    "liveTv.categories": "频道",
    "podcasts.title": "新闻播客",
    "podcasts.latest": "最新节目",
    "factCheck.verified": "已验证",
    "factCheck.unverified": "未验证",
    "factCheck.disputed": "有争议",
    "factCheck.satire": "讽刺",
    "common.loadMore": "加载更多",
    "common.loading": "加载中...",
    "common.error": "出了点问题",
    "common.retry": "重试",
    "common.back": "返回",
    "common.share": "分享",
    "common.save": "保存",
    "common.saved": "已保存",
    "common.readMore": "阅读原文",
    "common.min": "分钟阅读",
  },
  ja: {
    "nav.home": "ホーム",
    "nav.search": "検索",
    "nav.favorites": "お気に入り",
    "nav.liveTv": "ライブTV",
    "nav.podcasts": "ポッドキャスト",
    "nav.weather": "天気",
    "nav.stocks": "株式市場",
    "nav.elections": "選挙",
    "nav.crypto": "暗号通貨",
    "nav.language": "言語",
    "home.title": "トップニュース",
    "home.subtitle": "世界の最新ニュース",
    "home.trending": "トレンド",
    "home.forYou": "おすすめ",
    "search.placeholder": "ニュースを検索...",
    "search.title": "検索結果",
    "search.noResults": "結果が見つかりません",
    "favorites.title": "保存した記事",
    "favorites.empty": "保存した記事はまだありません",
    "favorites.emptyHint": "記事のハートアイコンをタップして保存",
    "weather.title": "天気",
    "weather.forecast": "5日間の予報",
    "stocks.title": "株式市場",
    "stocks.gainers": "値上がりトップ",
    "stocks.losers": "値下がりトップ",
    "crypto.title": "暗号通貨",
    "crypto.marketCap": "時価総額",
    "crypto.volume": "24時間取引量",
    "elections.title": "選挙結果",
    "elections.live": "ライブ",
    "liveTv.title": "ライブニュース",
    "liveTv.categories": "チャンネル",
    "podcasts.title": "ニュースポッドキャスト",
    "podcasts.latest": "最新エピソード",
    "factCheck.verified": "検証済み",
    "factCheck.unverified": "未検証",
    "factCheck.disputed": "議論の余地あり",
    "factCheck.satire": "風刺",
    "common.loadMore": "もっと見る",
    "common.loading": "読み込み中...",
    "common.error": "問題が発生しました",
    "common.retry": "再試行",
    "common.back": "戻る",
    "common.share": "共有",
    "common.save": "保存",
    "common.saved": "保存済み",
    "common.readMore": "元記事を読む",
    "common.min": "分で読める",
  },
  ar: {
    "nav.home": "الرئيسية",
    "nav.search": "بحث",
    "nav.favorites": "المفضلة",
    "nav.liveTv": "بث مباشر",
    "nav.podcasts": "بودكاست",
    "nav.weather": "الطقس",
    "nav.stocks": "الأسهم",
    "nav.elections": "الانتخابات",
    "nav.crypto": "العملات الرقمية",
    "nav.language": "اللغة",
    "home.title": "أخبار عاجلة",
    "home.subtitle": "آخر الأخبار من حول العالم",
    "home.trending": "الرائج",
    "home.forYou": "لك",
    "search.placeholder": "بحث في الأخبار...",
    "search.title": "نتائج البحث",
    "search.noResults": "لم يتم العثور على نتائج",
    "favorites.title": "المقالات المحفوظة",
    "favorites.empty": "لا توجد مقالات محفوظة بعد",
    "favorites.emptyHint": "اضغط على أيقونة القلب على أي مقال لحفظه",
    "weather.title": "الطقس",
    "weather.forecast": "توقعات 5 أيام",
    "stocks.title": "سوق الأسهم",
    "stocks.gainers": "الأكثر ارتفاعاً",
    "stocks.losers": "الأكثر انخفاضاً",
    "crypto.title": "العملات الرقمية",
    "crypto.marketCap": "القيمة السوقية",
    "crypto.volume": "حجم التداول 24 ساعة",
    "elections.title": "نتائج الانتخابات",
    "elections.live": "مباشر",
    "liveTv.title": "بث تلفزيوني مباشر",
    "liveTv.categories": "القنوات",
    "podcasts.title": "بودكاست الأخبار",
    "podcasts.latest": "أحدث الحلقات",
    "factCheck.verified": "موثق",
    "factCheck.unverified": "غير موثق",
    "factCheck.disputed": "مثار جدل",
    "factCheck.satire": "سخرية",
    "common.loadMore": "تحميل المزيد",
    "common.loading": "جاري التحميل...",
    "common.error": "حدث خطأ ما",
    "common.retry": "إعادة المحاولة",
    "common.back": "رجوع",
    "common.share": "مشاركة",
    "common.save": "حفظ",
    "common.saved": "محفوظ",
    "common.readMore": "اقرأ الأصلي",
    "common.min": "دقيقة قراءة",
  },
  hi: {
    "nav.home": "होम",
    "nav.search": "खोजें",
    "nav.favorites": "पसंदीदा",
    "nav.liveTv": "लाइव टीवी",
    "nav.podcasts": "पॉडकास्ट",
    "nav.weather": "मौसम",
    "nav.stocks": "शेयर बाजार",
    "nav.elections": "चुनाव",
    "nav.crypto": "क्रिप्टो",
    "nav.language": "भाषा",
    "home.title": "शीर्ष समाचार",
    "home.subtitle": "दुनिया भर से ताज़ा खबरें",
    "home.trending": "ट्रेंडिंग",
    "home.forYou": "आपके लिए",
    "search.placeholder": "समाचार खोजें...",
    "search.title": "खोज परिणाम",
    "search.noResults": "कोई परिणाम नहीं मिला",
    "favorites.title": "सहेजे गए लेख",
    "favorites.empty": "अभी तक कोई लेख सहेजा नहीं गया",
    "favorites.emptyHint": "किसी भी लेख पर दिल के आइकन पर टैप करें",
    "weather.title": "मौसम",
    "weather.forecast": "5-दिन का पूर्वानुमान",
    "stocks.title": "शेयर बाजार",
    "stocks.gainers": "सबसे ज्यादा बढ़ने वाले",
    "stocks.losers": "सबसे ज्यादा गिरने वाले",
    "crypto.title": "क्रिप्टोकरेंसी",
    "crypto.marketCap": "बाज़ार पूंजी",
    "crypto.volume": "24h वॉल्यूम",
    "elections.title": "चुनाव परिणाम",
    "elections.live": "लाइव",
    "liveTv.title": "लाइव टीवी समाचार",
    "liveTv.categories": "चैनल",
    "podcasts.title": "समाचार पॉडकास्ट",
    "podcasts.latest": "नवीनतम एपिसोड",
    "factCheck.verified": "सत्यापित",
    "factCheck.unverified": "असत्यापित",
    "factCheck.disputed": "विवादित",
    "factCheck.satire": "व्यंग्य",
    "common.loadMore": "और लोड करें",
    "common.loading": "लोड हो रहा है...",
    "common.error": "कुछ गड़बड़ हुई",
    "common.retry": "पुनः प्रयास करें",
    "common.back": "वापस",
    "common.share": "साझा करें",
    "common.save": "सहेजें",
    "common.saved": "सहेजा गया",
    "common.readMore": "मूल पढ़ें",
    "common.min": "मिनट पढ़ें",
  },
  pt: {
    "nav.home": "Início",
    "nav.search": "Pesquisar",
    "nav.favorites": "Favoritos",
    "nav.liveTv": "TV Ao Vivo",
    "nav.podcasts": "Podcasts",
    "nav.weather": "Clima",
    "nav.stocks": "Bolsa",
    "nav.elections": "Eleições",
    "nav.crypto": "Cripto",
    "nav.language": "Idioma",
    "home.title": "Principais Notícias",
    "home.subtitle": "As últimas notícias do mundo todo",
    "home.trending": "Em Alta",
    "home.forYou": "Para Você",
    "search.placeholder": "Pesquisar notícias...",
    "search.title": "Resultados da Pesquisa",
    "search.noResults": "Nenhum resultado encontrado",
    "favorites.title": "Artigos Salvos",
    "favorites.empty": "Nenhum artigo salvo ainda",
    "favorites.emptyHint": "Toque no ícone de coração para salvar",
    "weather.title": "Clima",
    "weather.forecast": "Previsão de 5 Dias",
    "stocks.title": "Mercado de Ações",
    "stocks.gainers": "Maiores Altas",
    "stocks.losers": "Maiores Baixas",
    "crypto.title": "Criptomoedas",
    "crypto.marketCap": "Capitalização",
    "crypto.volume": "Volume 24h",
    "elections.title": "Resultados das Eleições",
    "elections.live": "AO VIVO",
    "liveTv.title": "TV Ao Vivo",
    "liveTv.categories": "Canais",
    "podcasts.title": "Podcasts de Notícias",
    "podcasts.latest": "Últimos Episódios",
    "factCheck.verified": "Verificado",
    "factCheck.unverified": "Não Verificado",
    "factCheck.disputed": "Disputado",
    "factCheck.satire": "Sátira",
    "common.loadMore": "Carregar Mais",
    "common.loading": "Carregando...",
    "common.error": "Algo deu errado",
    "common.retry": "Tentar Novamente",
    "common.back": "Voltar",
    "common.share": "Compartilhar",
    "common.save": "Salvar",
    "common.saved": "Salvo",
    "common.readMore": "Ler Original",
    "common.min": "min de leitura",
  },
};

export function getTranslation(lang: string, key: string): string {
  const translations = TRANSLATIONS[lang] || TRANSLATIONS["en"];
  return translations[key] || TRANSLATIONS["en"][key] || key;
}
